// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI-9XeRiKIJ8gnoTmU80qktEvfQAhPyLs',
    appId: '1:642992823261:web:bd7ea7c9838c3bb22cb434',
    messagingSenderId: '642992823261',
    projectId: 'flood-alert-and-warning-app',
    authDomain: 'flood-alert-and-warning-app.firebaseapp.com',
    storageBucket: 'flood-alert-and-warning-app.firebasestorage.app',
    measurementId: 'G-9JF2B1E0HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgZxgqUFoBLylzNUDyMS_ggiWGNYpnqMo',
    appId: '1:642992823261:android:c20bec651ae9b3e42cb434',
    messagingSenderId: '642992823261',
    projectId: 'flood-alert-and-warning-app',
    storageBucket: 'flood-alert-and-warning-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAViY6N7IdTa1LN40D_B4WTzrZi1EIQcWw',
    appId: '1:642992823261:ios:6d0c00a2126e50e92cb434',
    messagingSenderId: '642992823261',
    projectId: 'flood-alert-and-warning-app',
    storageBucket: 'flood-alert-and-warning-app.firebasestorage.app',
    iosBundleId: 'com.example.csProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAViY6N7IdTa1LN40D_B4WTzrZi1EIQcWw',
    appId: '1:642992823261:ios:6d0c00a2126e50e92cb434',
    messagingSenderId: '642992823261',
    projectId: 'flood-alert-and-warning-app',
    storageBucket: 'flood-alert-and-warning-app.firebasestorage.app',
    iosBundleId: 'com.example.csProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI-9XeRiKIJ8gnoTmU80qktEvfQAhPyLs',
    appId: '1:642992823261:web:fc9c4d97a4d583512cb434',
    messagingSenderId: '642992823261',
    projectId: 'flood-alert-and-warning-app',
    authDomain: 'flood-alert-and-warning-app.firebaseapp.com',
    storageBucket: 'flood-alert-and-warning-app.firebasestorage.app',
    measurementId: 'G-Z7Z03TRX89',
  );
}
